.PHONY: all
.PHONY: install
.PHONY: clean

ISP_PREFIX ?= $(HOME)/.local/isp/

all: build/Makefile
	$(MAKE) -C build

build/Makefile:
	mkdir build
	cd build; ../configure --prefix=$(ISP_PREFIX)

install:
	$(MAKE) -C build install

clean:
	$(RM) -r build

